In [ ]:
#Importing All Required Libraries
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
#Uploading The File .csv aka Dataset
from google.colab import files
files.upload()

Saving Manga_Data.csv to Manga_Data.csv


{'Manga_Data.csv': b'Rank,Title,Genre,Author,Synopsis,Volume,Rating,Status\r\n1,Berserk,"Action, Adventure, Demons, Drama, Fantasy, Horror, Supernatural, Military, Psychological, Seinen",Arakawa Hiromu,"Guts, a former mercenary now known as the ""Black Swordsman,"" is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings.\n\nSetting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him?and his loved one?of their humanity.",40,9.38,Publishing\r\n2,One Piece,"Action, Adventure, Comedy, Fantasy, Shounen, Super Power",Oda

In [ ]:
#Displaying all data inside dataset
df = pd.read_csv('Manga_Data.csv')
df

Rank                                    Title  ... Rating      Status
0      1                                  Berserk  ...   9.38  Publishing
1      2                                One Piece  ...   9.15  Publishing
2      3                      Fullmetal Alchemist  ...   9.08    Finished
3      4                               Grand Blue  ...   9.04  Publishing
4      5                                Slam Dunk  ...   9.02    Finished
5      6                             Vinland Saga  ...   8.94  Publishing
6      7                                Haikyuu!!  ...   8.90    Finished
7      8                                      GTO  ...   8.89    Finished
8      9                          3-gatsu no Lion  ...   8.89  Publishing
9     10                           Koe no Katachi  ...   8.86    Finished
10    11                            Made in Abyss  ...   8.83  Publishing
11    12                                 Mushishi  ...   8.76    Finished
12    13                            One Punch-Man  ...   8.73  Publishing
13    14                               Death Note  ...   8.72    Finished
14    15                                    Akira  ...   8.71    Finished
15    16                          Tokyo Revengers  ...   8.70  Publishing
16    17                  Shoujo Shuumatsu Ryokou  ...   8.69    Finished
17    18                          Hunter x Hunter  ...   8.68  Publishing
18    19                                     Beck  ...   8.68    Finished
19    20                                   ReLIFE  ...   8.67    Finished
20    21                              Blue Period  ...   8.66  Publishing
21    22                             Chainsaw Man  ...   8.66    Finished
22    23                               Dorohedoro  ...   8.65    Finished
23    24                              Banana Fish  ...   8.64    Finished
24    25                        Sousou no Frieren  ...   8.63  Publishing
25    26                                     Aria  ...   8.63    Finished
26    27                  Shigatsu wa Kimi no Uso  ...   8.62    Finished
27    28                           Mob Psycho 100  ...   8.60    Finished
28    29                       Shingeki no Kyojin  ...   8.59    Finished
29    30  Rurouni Kenshin: Meiji Kenkaku Romantan  ...   8.59    Finished
30    31                               Skip Beat!  ...   8.59  Publishing
31    32                                  Gintama  ...   8.58    Finished
32    33                  Neon Genesis Evangelion  ...   8.55    Finished
33    34                           Jujutsu Kaisen  ...   8.53  Publishing
34    35                              Tokyo Ghoul  ...   8.52    Finished
35    36                             Golden Kamuy  ...   8.52  Publishing
36    37                             Fruit Basket  ...   8.51    Finished
37    38                             Eyeshield 21  ...   8.50    Finished
38    39                 Gekkan Shoujo Nozaki-kun  ...   8.49  Publishing
39    40                              Hinamatsuri  ...   8.49    Finished
40    41                                 Horimiya  ...   8.47    Finished
41    42                           Kimi no Na wa.  ...   8.42    Finished
42    43                                 Kiseijuu  ...   8.40    Finished
43    44                               SKET Dance  ...   8.38    Finished
44    45                                 Nichijou  ...   8.34    Finished
45    46                              Gin no Saji  ...   8.33    Finished
46    47                                 Beastars  ...   8.33    Finished
47    48                         Kimetsu no Yaiba  ...   8.28    Finished
48    49                             Black Lagoon  ...   8.27  Publishing
49    50                          Sounan desu ka?  ...   7.26  Publishing
50    51                           Hajime no Ippo  ...   8.68  Publishing

[51 rows x 8 columns]

In [ ]:
#creating new column for Comics ID ps:You need this!
df['Manga_id'] = range(0,51)

In [ ]:
#checking if the column has been created
df

Rank                                    Title  ...      Status Manga_id
0      1                                  Berserk  ...  Publishing        0
1      2                                One Piece  ...  Publishing        1
2      3                      Fullmetal Alchemist  ...    Finished        2
3      4                               Grand Blue  ...  Publishing        3
4      5                                Slam Dunk  ...    Finished        4
5      6                             Vinland Saga  ...  Publishing        5
6      7                                Haikyuu!!  ...    Finished        6
7      8                                      GTO  ...    Finished        7
8      9                          3-gatsu no Lion  ...  Publishing        8
9     10                           Koe no Katachi  ...    Finished        9
10    11                            Made in Abyss  ...  Publishing       10
11    12                                 Mushishi  ...    Finished       11
12    13                            One Punch-Man  ...  Publishing       12
13    14                               Death Note  ...    Finished       13
14    15                                    Akira  ...    Finished       14
15    16                          Tokyo Revengers  ...  Publishing       15
16    17                  Shoujo Shuumatsu Ryokou  ...    Finished       16
17    18                          Hunter x Hunter  ...  Publishing       17
18    19                                     Beck  ...    Finished       18
19    20                                   ReLIFE  ...    Finished       19
20    21                              Blue Period  ...  Publishing       20
21    22                             Chainsaw Man  ...    Finished       21
22    23                               Dorohedoro  ...    Finished       22
23    24                              Banana Fish  ...    Finished       23
24    25                        Sousou no Frieren  ...  Publishing       24
25    26                                     Aria  ...    Finished       25
26    27                  Shigatsu wa Kimi no Uso  ...    Finished       26
27    28                           Mob Psycho 100  ...    Finished       27
28    29                       Shingeki no Kyojin  ...    Finished       28
29    30  Rurouni Kenshin: Meiji Kenkaku Romantan  ...    Finished       29
30    31                               Skip Beat!  ...  Publishing       30
31    32                                  Gintama  ...    Finished       31
32    33                  Neon Genesis Evangelion  ...    Finished       32
33    34                           Jujutsu Kaisen  ...  Publishing       33
34    35                              Tokyo Ghoul  ...    Finished       34
35    36                             Golden Kamuy  ...  Publishing       35
36    37                             Fruit Basket  ...    Finished       36
37    38                             Eyeshield 21  ...    Finished       37
38    39                 Gekkan Shoujo Nozaki-kun  ...  Publishing       38
39    40                              Hinamatsuri  ...    Finished       39
40    41                                 Horimiya  ...    Finished       40
41    42                           Kimi no Na wa.  ...    Finished       41
42    43                                 Kiseijuu  ...    Finished       42
43    44                               SKET Dance  ...    Finished       43
44    45                                 Nichijou  ...    Finished       44
45    46                              Gin no Saji  ...    Finished       45
46    47                                 Beastars  ...    Finished       46
47    48                         Kimetsu no Yaiba  ...    Finished       47
48    49                             Black Lagoon  ...  Publishing       48
49    50                          Sounan desu ka?  ...  Publishing       49
50    51                           Hajime no Ippo  ...  Publishing       50

[51 rows x 9 columns]

In [ ]:
#Collecting all Colmns that you want to use in cosine similarity
Columns = ['Title', 'Genre', 'Synopsis']

In [ ]:
#Create Function to combine all of that(Previous Code) in singgle string
def get_important_feature(data):
  important_features = []
  for i in range(0, data.shape[0]):
    important_features.append(data['Title'][i]+' '+data['Genre'][i]+' '+data['Synopsis'][i])

  return important_features

In [ ]:
#Create Column 'important_features' to hold 'def' function
df['important_features'] = get_important_feature(df)

df.head(3)

Rank  ...                                 important_features
0     1  ...  Berserk Action, Adventure, Demons, Drama, Fant...
1     2  ...  One Piece Action, Adventure, Comedy, Fantasy, ...
2     3  ...  Fullmetal Alchemist Action, Adventure, Comedy,...

[3 rows x 10 columns]

In [ ]:
#Conver Text the text to a matrix token
cm = CountVectorizer().fit_transform(df['important_features'])

In [ ]:
cm.shape

(51, 2418)

In [ ]:
#Get cosine similarity matrix from the matrix token
cs = cosine_similarity(cm)

#print cosine similarity matrix ps: 1 indicates 100% similarity on that index and row
print(cs)

[[1.         0.50265078 0.43599762 ... 0.36562352 0.07290148 0.31700776]
 [0.50265078 1.         0.49069284 ... 0.41811236 0.07366381 0.37802057]
 [0.43599762 0.49069284 1.         ... 0.42051095 0.08447234 0.33652258]
 ...
 [0.36562352 0.41811236 0.42051095 ... 1.         0.04652421 0.21256976]
 [0.07290148 0.07366381 0.08447234 ... 0.04652421 1.         0.04501491]
 [0.31700776 0.37802057 0.33652258 ... 0.21256976 0.04501491 1.        ]]


In [ ]:
cs.shape

(51, 51)

In [ ]:
#Getting the comic title
title = 'Grand Blue'

#finding the comic id
manga_id = df[df.Title == title]['Manga_id'].values[0]

In [ ]:
#Create List Of Enumeration for similarity score like this [ (movie_id, similarity scores), (...) ]
scores = list(enumerate(cs[manga_id]))

In [ ]:
#Sort the score
sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
sorted_scores = sorted_scores[1:]

In [ ]:
#print the sorted scores
print(sorted_scores)

[(21, 0.5955525858169786), (8, 0.5925256930454874), (4, 0.5878020584265118), (19, 0.5864025277301438), (22, 0.5617090762127892), (35, 0.545567199574031), (34, 0.5447052821040768), (47, 0.5430564879132628), (6, 0.5357623420642402), (5, 0.5333125869479909), (29, 0.5255768421716767), (26, 0.5154835307167936), (20, 0.5086414855156142), (32, 0.5083846635965089), (45, 0.5022258684949831), (18, 0.5007478915389811), (39, 0.48968382224069734), (9, 0.48502467130838794), (11, 0.4845337748382722), (37, 0.48284348386617326), (14, 0.47531918718048255), (13, 0.4743540404763271), (31, 0.4715808645057122), (2, 0.46516156471474046), (23, 0.4647087002360882), (41, 0.45977237402755927), (1, 0.4597281885126788), (16, 0.45474007664553684), (46, 0.453857537973256), (10, 0.44453750078924376), (12, 0.44096716456814095), (30, 0.44059071206468614), (25, 0.4358967891149553), (0, 0.43463072076438103), (7, 0.4314259346304222), (28, 0.4251543389089337), (17, 0.42396693275112873), (48, 0.4224348215419493), (36, 0.413

In [ ]:
#Create Loop to print recomended movies
j=0
print('7 Most Recomended Manga After Reading', title, 'are:\n')
for item in sorted_scores:
  manga_title = df[df.Manga_id == item[0]]['Title'].values[0]
  print(j+1, manga_title)
  j=j+1
  if j>6:
    break

7 Most Recomended Manga After Reading Grand Blue are:

1 Chainsaw Man
2 3-gatsu no Lion
3 Slam Dunk
4 ReLIFE
5 Dorohedoro
6 Golden Kamuy
7 Tokyo Ghoul
